# Entry and exit messages
Joins:
  default:
    joinMessagesEnabled: true
    JoinMessage: '&5TChat &e> &7[&a+&7] &a%player% &7has entered the server'
    quitMessagesEnabled: true
    QuitMessage: '&5TChat &e> &7[&c-&7] &c%player% &7has left the server'
    entryCommandsEnabled: true
    entryCommands:
      - "say Hi %player%! :)"
    quitCommandsEnabled: true
    quitCommands:
      - "broadcast Bye %player%! :("
    Particles:
      Join:
        joinParticlesEnabled: true
        joinParticlesType: "FLAME"
      Quit:
        quitParticlesEnabled: true
        quitParticlesType: "CLOUD"
    Sounds:
      Join:
        joinSoundEnabled: true
        joinSoundType: "ENTITY_PLAYER_LEVELUP"
      Quit:
        quitSoundEnabled: true
        quitSoundType: "ENTITY_GENERIC_EXPLODE"
    Titles:
      enabled: true
      title: "&5Welcome to the server!"
      subtitle: "&5TChat &e- &5Tect.host"
  op:
    joinMessagesEnabled: true
    JoinMessage: '&5TChat &e> &7[&a+&7] &a%player% &7has entered the server'
    quitMessagesEnabled: true
    QuitMessage: '&5TChat &e> &7[&c-&7] &c%player% &7has left the server'
    entryCommandsEnabled: true
    entryCommands:
      - "say Hi %player%! :)"
    quitCommandsEnabled: true
    quitCommands:
      - "broadcast Bye %player%! :("
    Particles:
      Join:
        joinParticlesEnabled: true
        joinParticlesType: "FLAME"
      Quit:
        quitParticlesEnabled: true
        quitParticlesType: "CLOUD"
    Sounds:
      Join:
        joinSoundEnabled: true
        joinSoundType: "ENTITY_PLAYER_LEVELUP"
      Quit:
        quitSoundEnabled: true
        quitSoundType: "ENTITY_GENERIC_EXPLODE"
    Titles:
      enabled: true
      title: "&5Welcome to the server!"
      subtitle: "&5TChat &e- &5Tect.host"
  
# Private message format
Msg:
  # Sent message
  msgSent: '&5&l! &a<sender> &e&l> &a<recipient>&7: &f<message>'
  # Received message
  msgReceived: '&5&l! &a<sender> &e&l> &a<recipient>&7: &f<message>'
  
# HelpOp command format
Help:
  helpopFormat: '&4[HelpOp] %tchat_prefix%<player>%tchat_suffix%: &c<message>'
  
# Reply message format
Reply:
  # Sent message
  replySent: '&5&l! &a<sender> &e&l> &a<recipient>&7: &f<message>'
  # Received message
  replyReceived: '&5&l! &a<sender> &e&l> &a<recipient>&7: &f<message>'
  
# Announcement formats
Announcements:
  # Broadcast format
  broadcastFormat: '&4[Broadcast] &a%s'
  # Warning format
  warningFormat: '&4[Warning] &a%s'
  # Announcement format
  announcementFormat: '&4[Announcement] &a%s'
  # /me command format
  meFormat: '&5*&f%player% &7%s'
  
# Anti-advertising configuration
AntiAdvertising:
  # Option to disable all 3 functions
  antiAdvertisingEnabled: true
  # Blocks IPv4 addresses, for example, 192.168.1.50
  ipv4_blocked: true
  # Blocks domains, for example, tect.host or google.com
  domain_blocked: true
  # Blocks links, for example, https://tect.host/ or https://google.com (also blocks HTTP links)
  link_blocked: true
  
# Message displayed to players when entering the server
Motd:
  # Option to disable this function
  motdEnabled: true
  # Message
  motdMessage:
  - '&aWelcome to &5Tect.host&a!'
  - ''
  - '&aGet help in &5https://tect.host/'
  - '&5TChat &a- &5Tect.host'
  
# StaffChat format
Staff:
  format: '&d[SC] &a%player% &e>> &f%message%'
  staff_chat_join_message: '&5TChat &e> &aYou are now in the Staff channel.'
  staff_chat_leave_message: '&5TChat &e> &cYou have left the Staff channel.'
  
# AdminChat format
Admin:
  format: '&d[SC] &a%player% &e>> &f%message%'
  admin_chat_join_message: '&5TChat &e> &aYou are now in the Admin channel.'
  admin_chat_leave_message: '&5TChat &e> &cYou have left the Admin channel.'
  
# Having this option causes several TChat functions such as nickname and chatcolor to not work.
hover:
  op:
    enabled: true # enable/disable the group
    # The group hover text
    hoverText:
      - "&5TChat &e- &5OP"
      - "&5Money %vault_eco_balance_formatted%"
      - ""
      - "&e&nClick here to send a private message"
      # The suggest command (on click)
    suggestCommand: "/msg %player% "
  admin:
    enabled: true
      - "&5TChat &e- &5Admin"
      - "&5Money %vault_eco_balance_formatted%"
      - ""
      - "&e&nClick here to send a private message"
    suggestCommand: "/msg %player% "
  vip:
    enabled: true
    hoverText:
      - "&5TChat &e- &5VIP"
      - "&5Money %vault_eco_balance_formatted%"
      - ""
      - "&e&nClick here to send a private message"
    suggestCommand: "/msg %player% "
  default:
    enabled: true
      - "&5TChat &e- &5Default"
      - "&5Money %vault_eco_balance_formatted%"
      - ""
      - "&e&nClick here to send a private message"
    suggestCommand: "/msg %player% "
  
# The mention sound
mention_sound: ENTITY_EXPERIENCE_ORB_PICKUP
  
# Other options
Other:
  # Option to disable the antibot
  # TChat's antibot prevents any player from sending messages until they move
  antibotEnabled: true
  # Option to configure chat cooldown
  # Time before a command can be typed again
  chatCooldownSeconds: 3
  # Option to disable antispam
  # Prevents sending identical or highly similar messages (over 75% similarity)
  antiSpamEnabled: true
  # Option to disable anticap
  # Converts uppercase letters to lowercase
  anticap_enabled: true
  # Option to disable anti unicode
  # Blocks all characters from basic Latin, including the '&' character
  anti_unicode: false
