name: TChat
version: 2.2
main: minealex.tchat.TChat

commands:
  chat:
    description: TChat command
  chatclear:
    description: Clear the chat
    aliases:
      - cc
  msg:
    description: Send a private message
    aliases:
      - tell
      - whisper
      - ewhisper
      - pm
      - emsg
  reply:
    description: Send a reply to a private message
    aliases:
      - r