name: TChat
version: 2.5.4
main: minealex.tchat.TChat

commands:
  chat:
    description: TChat command
  chatclear:
    description: Clear the chat
    aliases:
      - cc
  msg:
    description: Send a private message
    aliases:
      - tell
      - whisper
      - ewhisper
      - pm
      - emsg
  reply:
    description: Send a reply to a private message
    aliases:
      - r
  chatcolor:
    description: Set the chat color
  rules:
    description: See the rules
  list:
    description: See the online players
  broadcast:
    description: Send a broadcast in the chat
    aliases:
      - bcast
  warning:
    description: Send a warning in the chat
  announcement:
    description: Send a announcement in the chat
    aliases:
      - ann
  ping:
    description: See the ping
  me:
    description: Send a message with a different format
  checkcommand:
    description: Check if a command is banned
  staffchat:
    description: Toggle staff chat
    aliases:
      - sc
      - staffc
      - schat
  nick:
    description: Change the username's nick