name: TChat
version: 1.3
main: minealex.tchat.TChat
author: Mine_Alex
description: Chat format plugin
api-version: 1.8

commands:
  chat:
    description: TChat command
  chatclear:
    description: Clear the chat